# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Movie.create(title: "UP", release_year: "05/29/2009", genre: "Children's", director: "Pete Doctor", description: "Carl Fredricksen, a 78-year-old balloon salesman, is about to fulfill a lifelong dream. Tying thousands of balloons to his house, he flies away to the South American wilderness. But curmudgeonly Carl's worst nightmare comes true when he discovers a little boy named Russell is a stowaway aboard the balloon-powered house.")
Movie.create(title: "Big Hero 6", release_year: "11/07/2014", genre: "Children's", director: "Chris Williams", description: "Robotics nerd Hiro Hamada discovers an inflatable health care robot Baymax created in the past by his brother, Tadashi. After a terrible life-changing accident, Hiro and Baymax team up with four other nerds and save their hometown San Fransokyo from an evil super villain trying to take over with Hiro's invention.")
Movie.create(title: "Toy Story", release_year: "11/22/1995", genre: "Children's", director: "John Lasseter", description: "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy's bedroom.")
Movie.create(title: "Ratatouille", release_year: "06/29/2007", genre: "Children's", director: "Brad Bird", description: "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.")
Movie.create(title: "Spider-Man", release_year: "05/03/2002", genre: "Action", director: "Sam Raimi", description: "After being bitten by a genetically-modified spider, a shy teenager gains spider-like abilities that he uses to fight injustice as a masked superhero and face a vengeful enemy.")
Movie.create(title: "Grease", release_year: "07/07/1978", genre: "Musical", director: "Randal Kleiser", description: "The film depicts the lives of greaser Danny Zuko and Australian transfer student Sandy Olsson, who develop an attraction for each other during a summer romance.")
Movie.create(title: "Nightmare Before Christmas", release_year: "10/29/1993", genre: "Musical", director: "Henry Selick", description: "It tells the story of Jack Skellington, the King of 'Halloween Town', who stumbles upon 'Christmas Town' and schemes to take over the holiday")
Movie.create(title: "Harry Potter", release_year: "11/16/2001", genre: "Fantasy", director: "Chris Columbus", description: "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world. On his eleventh birthday, Harry Potter discovers that he is no ordinary boy.")
Movie.create(title: "Super Mario Bros", release_year: "04/05/2023", genre: "Fantasy", director: "Aaron Horvath", description: "The film features an origin story for the brothers Mario and Luigi, Italian-American plumbers who are transported to an alternate world and become entangled in a battle between the Mushroom Kingdom, led by Princess Peach, and the Koopas, led by Bowser.")
Movie.create(title: "Sleeping Beauty", release_year: "01/29/1959", genre: "Fantasy", director: "Clyde Geronimi", description: "Filled with jealousy, the evil witch Maleficent curses Princess Aurora to die on her 16th birthday. Thanks to Aurora's guardian fairies, she only falls into a deep sleep that can be ended with a kiss from her betrothed, Prince Phillip. To prevent Phillip from rescuing Aurora, Maleficent kidnaps and imprisons him. The good fairies are the last hope to free Phillip so that he can awaken Aurora.")
Review.create(user_id: 1, movie_id: 1, rating: 4, review: "Great movie. Not perfect!")
Review.create(user_id: 2, movie_id: 4, rating: 2, review: "Did not live up to the hype.")
Review.create(user_id: 1, movie_id: 6, rating: 1, review: "Worst film i've ever seen!")
Review.create(user_id: 1, movie_id: 3, rating: 5, review: "Greatest movie ever made!!!!")
